import fs from "node:fs";
import path from "node:path";
import { spawn } from "node:child_process";
import { config } from "../../config/index.js";

export interface MusicTrack {
  id: string;
  title: string;
  creator: string;
  source: string;
  license: string;
  attribution: string;
  mood: string;
  bpm: number;
  durationSec: number;
  path: string;
}

function run(args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn("ffmpeg", args, { stdio: ["ignore", "pipe", "pipe"] });
    let err = "";
    child.stderr.on("data", (d) => (err += d.toString()));
    child.on("close", (c) => (c === 0 ? resolve() : reject(new Error(err.slice(-400)))));
  });
}

/** Original generated beds — not third-party recordings. Safe to ship. */
export async function ensureBundledMusic(): Promise<MusicTrack[]> {
  const dir = path.join(config.dataDir, "music");
  fs.mkdirSync(dir, { recursive: true });
  const specs: { id: string; mood: string; bpm: number; freqs: number[]; title: string }[] = [
    { id: "cinematic-low", mood: "cinematic", bpm: 72, freqs: [110, 165, 220], title: "Low Horizon" },
    { id: "documentary-pad", mood: "documentary", bpm: 80, freqs: [98, 147, 196], title: "Quiet Archive" },
    { id: "pulse-warm", mood: "upbeat", bpm: 100, freqs: [130, 196, 261], title: "Warm Pulse" },
  ];
  const tracks: MusicTrack[] = [];
  for (const s of specs) {
    const file = path.join(dir, `${s.id}.wav`);
    if (!fs.existsSync(file)) {
      const inputs = s.freqs.flatMap((f, i) => ["-f", "lavfi", "-i", `sine=frequency=${f}:duration=90:sample_rate=44100`]);
      const mix = s.freqs.map((_, i) => `[${i}:a]volume=${0.12 / (i + 1)}[a${i}]`).join(";");
      const amix = s.freqs.map((_, i) => `[a${i}]`).join("") + `amix=inputs=${s.freqs.length}:duration=longest,volume=0.8,afade=t=in:d=1.5,afade=t=out:st=86:d=4`;
      await run(["-y", ...inputs, "-filter_complex", `${mix};${amix}`, "-ac", "2", file]);
    }
    tracks.push({
      id: s.id,
      title: s.title,
      creator: "Aether Studio",
      source: "bundled-original",
      license: "CC0-1.0 (original generated bed)",
      attribution: "Original instrumental generated by Aether Studio",
      mood: s.mood,
      bpm: s.bpm,
      durationSec: 90,
      path: file,
    });
  }
  fs.writeFileSync(path.join(dir, "catalog.json"), JSON.stringify(tracks.map(({ path: p, ...rest }) => ({ ...rest, path: path.relative(config.dataDir, p) })), null, 2));
  return tracks;
}

export function pickMusic(tracks: MusicTrack[], mood: string): MusicTrack {
  const m = mood.toLowerCase();
  return (
    tracks.find((t) => m.includes(t.mood) || t.mood.includes(m.split(/\s+/)[0] ?? "")) ||
    tracks.find((t) => t.mood === "documentary") ||
    tracks[0]
  );
}
